name: ROCm Build Test

on:
  #push:
  #  branches:
  #    - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
        matrix:
          rocm_version: [6.4.3, 7.0.2]
          include:
            - rocm_version: 6.4.3
              gpu_targets: "gfx1100,gfx1030,gfx942,gfx90a,gfx908"
            - rocm_version: 7.0.2
              gpu_targets: "gfx950,gfx1201,gfx1200,gfx1101,gfx1100,gfx1030,gfx942,gfx90a,gfx908"
    runs-on: ubuntu-latest
    container:
      image: rocm/dev-ubuntu-22.04:${{ matrix.rocm_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix unfortunate rocm container bug
        if: ${{ matrix.rocm_version == '7.0.2' }}
        run: |
          sed -i "s/7.0.2/30.10.2/" /etc/apt/sources.list.d/amdgpu.list 

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential git rocblas-dev hipblas-dev hipblaslt-dev
      
      - name: Configure CMake
        run: |
          cmake -S src -B build \
            -DWITH_ROCM=true \
            -DWITH_CUDA=false \
            -DGPU_TARGETS=${{ matrix.gpu_targets }}
      
      - name: Build
        run: cmake --build build

      - name: Build Summary
        if: always()
        run: |
          echo "ROCm ${{ matrix.rocm_version }} build complete: ${{ job.status }}"

